### ISSUE TITLE
Add some block previews

### ISSUE THREAD

**Issue by boehsermoe** [luyadev/luya-generic#11]
Based on https://github.com/luyadev/luya-module-cms/pull/148

**Comment by nadar** [comment]
Which blocks do you think need a preview? I don't think it makes sense for every block, but in general: yes 👍

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.
